# Site settings
title: We Have To Talk About Coding
email: ggohierroy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my cool blog about coding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ggohierroy.github.io" # the base hostname & protocol for your site
twitter_username: ggohierroy
github_username:  ggohierroy

# Build settings
markdown: kramdown
